TabloidMVC/Models/Post.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TabloidMVC.Models
{
    public class Post
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        [DisplayName("Header Image URL")]
        public string ImageLocation { get; set; }

        public DateTime CreateDateTime { get; set; }

        [DisplayName("Published")]
        [DataType(DataType.Date)]
        public DateTime? PublishDateTime { get; set; }

        public bool IsApproved { get; set; }

        [Required]
        [DisplayName("Category")]
        public int CategoryId { get; set; }
        public Category Category { get; set; }

        [DisplayName("Author")]
        public int UserProfileId { get; set; }
        public UserProfile UserProfile { get; set; }
    }
}

TabloidMVC/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.VisualBasic;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using TabloidMVC.Models;
using TabloidMVC.Models.ViewModels;
using TabloidMVC.Repositories;

namespace TabloidMVC.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ITagRepository _tagRepository;
        private readonly ISubscriptionRepository _subscriptionRepository;

        public PostController(IPostRepository postRepository, ICategoryRepository categoryRepository, ITagRepository tagRepository, ISubscriptionRepository subscriptionRepository)
        {
            _postRepository = postRepository;
            _categoryRepository = categoryRepository;
            _tagRepository = tagRepository;
            _subscriptionRepository = subscriptionRepository;
        }

        public IActionResult Index()
        {
            var posts = _postRepository.GetAllPublishedPosts();
            return View(posts);
        }

        public IActionResult MyPosts()
        {
            int userId = GetCurrentUserProfileId();
            var posts = _postRepository.GetUserPosts(userId);
            return View(posts);
        }

        public IActionResult Details(int id)
        {
            var post = _postRepository.GetPublishedPostById(id);
            List<Tag> tags = _tagRepository.GetTagsByPostId(id);
            if (post == null)
            {
                int userId = GetCurrentUserProfileId();
                post = _postRepository.GetUserPostById(id, userId);
                if (post == null)
                {
                    return NotFound();
                }
            }
            PostDetailsViewModel vm = new PostDetailsViewModel()
            {
                Post = post,
                Tags = tags
            };
            return View(vm);
        }

        public IActionResult Create()
        {
            var vm = new PostCreateViewModel();
            vm.CategoryOptions = _categoryRepository.GetAll();
            return View(vm);
        }

        [HttpPost]
        public IActionResult Create(PostCreateViewModel vm)
        {
            try
            {
                vm.Post.CreateDateTime = DateAndTime.Now;
                vm.Post.IsApproved = true;
                vm.Post.UserProfileId = GetCurrentUserProfileId();

                _postRepository.Add(vm.Post);

                return RedirectToAction("Details", new { id = vm.Post.Id });
            }
            catch
            {
                vm.CategoryOptions = _categoryRepository.GetAll();
                return View(vm);
            }
        }

        public IActionResult Edit(int id)
        {
            try
            {
                int userId = GetCurrentUserProfileId();
                Post post = _postRepository.GetPublishedPostById(id);
                List<Category> categories =  _categoryRepository.GetAll();
                if (post.UserProfileId != userId)
                {
                    throw new Exception();
                }
                else
                {
                    PostCreateViewModel vm = new PostCreateViewModel()
                    {
                        Post = post,
                        CategoryOptions = categories
                    };
                    return View(vm);
                }
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, PostCreateViewModel vm)
        {
            try
            {
            _postRepository.UpdatePost(vm.Post);

            return RedirectToAction("Index");
            }
            catch
            {
                return View(vm);
            }
        }

        // GET: Post/Delete/5
        public IActionResult Delete(int id)
        {
            try
            {
                int userId = GetCurrentUserProfileId();
                Post post = _postRepository.GetPublishedPostById(id);
                if (post.UserProfileId != userId)
                {
                    throw new Exception();
                }
                else
                {
                    return View(post);
                }

            }
            catch
            {
                return NotFound();
            }

        }

        // POST: Post/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, Post post)
        {
            try
            {
                _postRepository.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(post);
            }
        }

        private int GetCurrentUserProfileId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }


        public ActionResult Subscribe(int id)
        {
            // Need to return a view that functions as a form that allows users to fill in Comment info with
            // PostId should be based on the post routed from
            // UserProfileId should be based on the current user
            Subscription subscription = new Subscription();
            subscription.ProviderUserProfileId = id;
            subscription.SubscriberUserProfileId = GetCurrentUserProfileId();


            return View(subscription);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Subscribe(Subscription subscription, Post post)
        {
            subscription.BeginDateTime = DateAndTime.Now;
            subscription.EndDateTime = DateAndTime.Now;
            _subscriptionRepository.Add(subscription);

            return RedirectToAction("Details", new { id = post.Id });
        }

        



    }
}

TabloidMVC/Controllers/PostTagController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TabloidMVC.Models;
using TabloidMVC.Models.ViewModels;
using TabloidMVC.Repositories;

namespace TabloidMVC.Controllers
{
    public class PostTagController : Controller
    {
        private readonly IPostTagRepository _postTagRepository;
        private readonly ITagRepository _tagRepository;

        public PostTagController(
            IPostTagRepository postTagRepository,
            ITagRepository tagRepository)
        {
            _postTagRepository = postTagRepository;
            _tagRepository = tagRepository;
        }

        // GET: PostTagController
        public ActionResult Index()
        {
            return View();
        }

        // GET: PostTagController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PostTagController/Create
        public ActionResult Create(int id)
        {
            List<Tag> tags = _tagRepository.GetAllTags();
            PostTagViewModel vm = new PostTagViewModel()
            {
                PostTags = new List<int>(),
                Tags = tags,
                PostId = id
            };
            return View(vm);
        }

        // POST: PostTagController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PostTagViewModel vm)
        {
            if (vm.PostTags == null)
            {
                return RedirectToAction("Details", "Post", new { id = vm.PostId });
            }
            else
            {
                foreach (int postTag in vm.PostTags)
                {
                    PostTag pT = new PostTag();
                    pT.TagId = postTag;
                    pT.PostId = vm.PostId;
                    _postTagRepository.AddPostTag(pT);
                }
                return RedirectToAction("Details", "Post", new { id = vm.PostId });
            }
        }

        // GET: PostTagController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PostTagController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PostTagController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PostTagController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TabloidMVC/Views/Post/Create.cshtml
@model TabloidMVC.Models.ViewModels.PostCreateViewModel

@{
    ViewData["Title"] = "Create";
}



<div class="container pt-5">
    <div class="row justify-content-center">
        <div class="card col-md-12 col-lg-8">
            <h3 class="mt-3 text-primary text-center card-title">What do you have to say?</h3>
            <form class="mt-5 card-body" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Post.Title" class="control-label"></label>
                    <input asp-for="Post.Title" class="form-control" />
                    <span asp-validation-for="Post.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.ImageLocation" class="control-label"></label>
                    <input asp-for="Post.ImageLocation" class="form-control" />
                    <span asp-validation-for="Post.ImageLocation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.PublishDateTime" class="control-label"></label>
                    <input asp-for="Post.PublishDateTime" class="form-control" />
                    <span asp-validation-for="Post.PublishDateTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.CategoryId" class="control-label"></label>
                    <select asp-for="Post.CategoryId" class="form-control">
                        @foreach (var category in Model.CategoryOptions)
                        {
                            <option value="@category.Id">@category.Name</option>
                        }
                    </select>
                    <span asp-validation-for="Post.CategoryId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.Content" class="control-label"></label>
                    <textarea asp-for="Post.Content" rows="15" class="form-control post__content-input"></textarea>
                    <span asp-validation-for="Post.Content" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="SAVE" class="btn btn-primary btn-block" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TabloidMVC/Views/Post/Delete.cshtml
@model TabloidMVC.Models.Post

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageLocation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageLocation)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TabloidMVC/Views/Post/Details.cshtml
@model TabloidMVC.Models.ViewModels.PostDetailsViewModel

@{
    ViewData["Title"] = $"Post - {Model.Post.Title}";
}

<div class="container pt-5">
    <div class="post">
        <section class="px-3">
            <div class="row justify-content-between">
                <h1 class="text-secondary">@Model.Post.Title</h1>
                <h1 class="text-black-50">@Model.Post.Category.Name</h1>
            </div>
            <div class="row justify-content-between">
                <p class="text-secondary">
                    Written by @Model.Post.UserProfile.DisplayName
                    @*@using (Html.BeginForm("Subscribe", "PostConrtoller", new { id = "Subscribe" }, FormMethod.Post))
                    {*@
                        @*<input type = "Submit" class="submit" value="Subscribe" id="Subscribe" onclick="Subscribe(@Model.UserProfile.Id)" style=" font-size:" 1.2em" />}*@
                    <a asp-controller="Post"  asp-action="Subscribe" asp-route-id="@Model.Post.UserProfile.Id" class="btn btn-outline-primary mx-1" title="Subscribe">
            Subscribe
        </a>
                </p>
                
                <p class="text-black-50">Published on @Html.DisplayFor(model => model.Post.PublishDateTime)</p>
            </div>
            <div class="row">
                <a asp-action="Edit" asp-route-id="@Model.Post.Id" class="btn btn-outline-primary mx-1" title="Edit">
                    <i class="fas fa-pencil-alt"></i>
                </a>
                <a asp-action="Delete" asp-route-id="@Model.Post.Id" class="btn btn-outline-primary mx-1" title="Delete">
                    <i class="fas fa-trash"></i>
                </a>
                <a asp-controller="PostTag" asp-action="create" asp-route-id="@Model.Post.Id" class="btn btn-outline-primary mx-1" title="Manage Tags">
                    <i class="fas fa-tags"></i>
                </a>
                <a asp-controller="Comment" asp-action="Index" asp-route-id="@Model.Post.Id" class="btn btn-outline-primary mx-1" title="Comment">
                    View Comments
                </a>
                
            </div>
        </section>
        <hr />

        <h4>Tags</h4>
        <ul>
            @foreach (Tag tag in Model.Tags)
            {
                <li>@tag.Name</li>
            }
        </ul>

        @if (!string.IsNullOrWhiteSpace(Model.Post.ImageLocation))
        {
            <section class="row justify-content-center">
                <div>
                    <img src="@Model.Post.ImageLocation" />
                </div>
            </section>
        }
        <section class="row post__content">
            <p class="col-sm-12 mt-5">@Html.DisplayFor(model => model.Post.Content)</p>
        </section>
    </div>
</div>

TabloidMVC/Views/Post/Edit.cshtml
@model TabloidMVC.Models.ViewModels.PostCreateViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="container pt-5">
    <div class="row justify-content-center">
        <div class="card col-md-12 col-lg-8">
            <h3 class="mt-3 text-primary text-center card-title">Edit Your Post!</h3>
            <form class="mt-5 card-body" asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Post.Id" value=@Model.Post.Id />
                <input type="hidden" asp-for="CategoryOptions" value=@Model.CategoryOptions />
                <div class="form-group">
                    <label asp-for="Post.Title" class="control-label"></label>
                    <input asp-for="Post.Title" class="form-control" />
                    <span asp-validation-for="Post.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.ImageLocation" class="control-label"></label>
                    <input asp-for="Post.ImageLocation" class="form-control" />
                    <span asp-validation-for="Post.ImageLocation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.PublishDateTime" class="control-label"></label>
                    <input asp-for="Post.PublishDateTime" class="form-control" />
                    <span asp-validation-for="Post.PublishDateTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.CategoryId" class="control-label"></label>
                    <select asp-for="Post.CategoryId" class="form-control" value=@Model.Post.CategoryId>
                        @foreach (var category in Model.CategoryOptions)
                        {
                            <option value="@category.Id">@category.Name</option>
                        }
                    </select>
                    <span asp-validation-for="Post.CategoryId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.Content" class="control-label"></label>
                    <textarea asp-for="Post.Content" rows="15" class="form-control post__content-input"></textarea>
                    <span asp-validation-for="Post.Content" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="SAVE" class="btn btn-primary btn-block" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TabloidMVC/Views/Post/Index.cshtml
@model IEnumerable<TabloidMVC.Models.Post>

@{
    ViewData["Title"] = "Index";
}


<div class="container pt-5">
    <h1>Posts</h1>

    <p>
        <a class="btn btn-primary" asp-action="Create">New Post</a>
    </p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserProfileId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CategoryId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PublishDateTime)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserProfile.DisplayName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PublishDateTime)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="View">
                            <i class="fas fa-eye"></i>
                        </a>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="Edit">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="Delete">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

TabloidMVC/Views/Post/MyPosts.cshtml
@model IEnumerable<TabloidMVC.Models.Post>

@{
    ViewData["Title"] = "Index";
}


<div class="container pt-5">
    <h1>My Posts</h1>

    <p>
        <a class="btn btn-primary" asp-action="Create">New Post</a>
    </p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserProfileId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CategoryId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PublishDateTime)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserProfile.DisplayName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PublishDateTime)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="View">
                            <i class="fas fa-eye"></i>
                        </a>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="Edit">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="Delete">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

TabloidMVC/Views/Post/Subscribe.cshtml
@model TabloidMVC.Models.Subscription

@{
    ViewData["Title"] = "Subscribe";
}

@*<h1>Subscribe</h1>*@

<h3 class= "container pt-5">Are you sure you want to Subscribe?</h3>

@*<h4>Subscription</h4>*@
<hr />
<div class="row">
    <div class="col-md-4" >
        <form asp-action="Subscribe">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="SubscriberUserProfileId" class="form-control" />
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="ProviderUserProfileId" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Yes" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}